name: .NET Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: | 
        cd VoxelCore-SocketAPI
        dotnet restore
        
    - name: Build
      run: |
        cd VoxelCore-SocketAPI
        dotnet build --no-restore

    - name: Test
      run: | 
        cd VoxelCore-SocketAPI 
        dotnet test --no-build --verbosity normal

    - name: Create Archive
      run: |
        cd VoxelCore-SocketAPI
        dotnet publish -c Release -o ./output

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: VoxelCore-SocketAPI-linux
        path: VoxelCore-SocketAPI/output/*
