name: .NET Framework Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: |
        cd VoxelCore-SocketAPI
        nuget restore VoxelCore-SocketAPI.csproj

    - name: Build
      run: |
        cd VoxelCore-SocketAPI
        msbuild VoxelCore-SocketAPI.csproj /p:Configuration=Release /t:Build

    - name: Create Archive
      run: |
        cd VoxelCore-SocketAPI
        msbuild VoxelCore-SocketAPI.csproj /p:Configuration=Release /t:Publish /p:OutputPath=./output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VoxelCore-SocketAPI-windows
        path: VoxelCore-SocketAPI/output/*
