name: .NET Framework 4.7.2 Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: |
        cd VoxelCore-SocketAPI
        nuget restore VoxelCore-SocketAPI.csproj  # Adjust if using various project files

    - name: Build
      run: |
        cd VoxelCore-SocketAPI
        msbuild VoxelCore-SocketAPI.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2

    - name: Create Archive
      run: |
        cd VoxelCore-SocketAPI
        msbuild VoxelCore-SocketAPI.csproj /p:Configuration=Release /t:Publish /p:OutputPath=./output /p:TargetFrameworkVersion=v4.7.2

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VoxelCore-SocketAPI-windows
        path: VoxelCore-SocketAPI/output/*
